"use client";

import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
    Database,
    Share2,
    Search,
    Filter,
    Link as LinkIcon,
    Cpu,
    Clock
} from "lucide-react";
import { useInsights } from "@/hooks/useCivion";
import { cn } from "@/lib/utils";

export default function MemoryPage() {
    const { insights, loading } = useInsights(30);
    const [selected, setSelected] = useState<string | null>(null);

    return (
        <div className="space-y-10">
            <section>
                <div className="flex justify-between items-end">
                    <div>
                        <h1 className="text-4xl font-bold tracking-tight mb-2 pr-4">Intelligence Memory</h1>
                        <p className="text-slate-400 text-lg pr-4">Explore the semantic knowledge graph generated by your agents.</p>
                    </div>
                    <div className="flex gap-2">
                        <button className="px-4 py-2 glass rounded-xl text-xs font-bold flex items-center gap-2">
                            <Filter className="w-4 h-4" /> Filter
                        </button>
                        <button className="px-4 py-2 bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 rounded-xl text-xs font-bold flex items-center gap-2">
                            <Share2 className="w-4 h-4" /> Export Graph
                        </button>
                    </div>
                </div>
            </section>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 h-[600px]">
                {/* Graph Visualization (Mock SVG) */}
                <div className="lg:col-span-2 glass rounded-3xl relative overflow-hidden flex items-center justify-center p-10 bg-[radial-gradient(circle_at_center,rgba(99,102,241,0.05)_0%,transparent_70%)]">
                    <svg className="w-full h-full text-slate-700/20" viewBox="0 0 800 500">
                        {/* Random connections */}
                        <line x1="100" y1="100" x2="300" y2="200" stroke="currentColor" strokeWidth="1" />
                        <line x1="300" y1="200" x2="500" y2="150" stroke="currentColor" strokeWidth="1" />
                        <line x1="300" y1="200" x2="250" y2="400" stroke="currentColor" strokeWidth="1" />
                        <line x1="500" y1="150" x2="650" y2="300" stroke="currentColor" strokeWidth="1" />

                        {/* Animated Node Pings */}
                        <circle cx="100" cy="100" r="4" fill="#6366f1" className="animate-pulse" />
                        <circle cx="300" cy="200" r="6" fill="#06b6d4" className="animate-pulse [animation-delay:0.5s]" />
                        <circle cx="500" cy="150" r="5" fill="#a855f7" className="animate-pulse [animation-delay:1s]" />
                        <circle cx="250" cy="400" r="4" fill="#eab308" className="animate-pulse [animation-delay:1.5s]" />
                        <circle cx="650" cy="300" r="5" fill="#f43f5e" className="animate-pulse [animation-delay:2s]" />

                        {/* Text labels */}
                        <text x="115" y="105" fill="gray" fontSize="10" className="font-mono">NODE_0x1A</text>
                        <text x="315" y="205" fill="gray" fontSize="10" className="font-mono">NODE_0x2F</text>
                        <text x="515" y="155" fill="gray" fontSize="10" className="font-mono">NODE_0x7C</text>
                    </svg>

                    <div className="absolute top-6 left-6 text-[10px] font-bold text-slate-500 uppercase tracking-widest bg-black/40 px-3 py-1 rounded-full border border-white/5">
                        Live Semantic Mesh
                    </div>
                </div>

                {/* Insight Detail Sidebar */}
                <div className="lg:col-span-1 flex flex-col gap-4 overflow-y-auto pr-2 scrollbar-hide">
                    {loading ? (
                        [1, 2, 3, 4].map(i => <div key={i} className="h-24 glass animate-pulse rounded-2xl" />)
                    ) : (
                        insights.map((insight: any) => (
                            <motion.div
                                key={insight.id}
                                onClick={() => setSelected(insight.id)}
                                className={cn(
                                    "p-4 rounded-2xl border transition-all cursor-pointer group",
                                    selected === insight.id ? "bg-indigo-500/10 border-indigo-500/30" : "glass border-transparent hover:border-white/10"
                                )}
                            >
                                <div className="flex items-start gap-3">
                                    <div className="p-2 rounded-lg bg-white/5 text-slate-400 group-hover:text-indigo-400 transition-colors">
                                        <Database className="w-4 h-4" />
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <h4 className="text-sm font-bold truncate mb-1">{insight.title}</h4>
                                        <div className="flex items-center gap-2 text-[10px] text-slate-500 font-medium">
                                            <Cpu className="w-3 h-3" /> {insight.agent_name}
                                            <span>•</span>
                                            <Clock className="w-3 h-3" /> {new Date(insight.created_at).toLocaleDateString()}
                                        </div>
                                    </div>
                                </div>
                            </motion.div>
                        ))
                    )}
                </div>
            </div>
        </div>
    );
}
