"""
CIVION — Builder Service
Handles dynamic code generation for new agents.
"""

import os
import logging
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger("civion.builder")

AGENT_TEMPLATE = """\"\"\"
CIVION — {class_name}
Auto-generated by the Agent Builder.
\"\"\"

from civion.agents.base_agent import BaseAgent, AgentResult

class {class_name}(BaseAgent):
    name: str = "{name}"
    description: str = "{description}"
    personality: str = "{personality}"
    interval: int = {interval}
    tools_allowed: list[str] = {tools}
    tags: list[str] = {tags}

    async def execute_task(self) -> AgentResult:
        \"\"\"{prompt}\"\"\"
        from civion.services.llm_service import llm
        
        # Context includes personality and memory (from BaseAgent.observe)
        context = await self.observe()
        
        prompt = f\"\"\"
        Objective: {description}
        Prompt: {prompt}
        
        Recent Memory: {{context['recent_memory']}}
        \"\"\"
        
        try:
            response = await llm.generate(prompt, system=self.personality_prompt())
            return AgentResult(success=True, title=self.name, content=response)
        except Exception as e:
            return AgentResult(success=False, content=f"Build-agent failed: {{e}}")
"""

class BuilderService:
    def __init__(self, agents_dir: str = "civion/agents"):
        self.agents_dir = Path(agents_dir)

    async def build_agent(
        self, 
        name: str, 
        description: str, 
        personality: str, 
        interval: int, 
        prompt: str,
        tools: List[str],
        tags: List[str]
    ) -> bool:
        """Generate a new agent .py file and save it to the agents directory."""
        class_name = "".join(x for x in name.title() if not x.isspace())
        if not class_name.endswith("Agent"):
            class_name += "Agent"

        file_name = f"{name.lower().replace(' ', '_')}.py"
        file_path = self.agents_dir / file_name

        if file_path.exists():
            logger.warning("Agent file %s already exists, overwriting.", file_name)

        content = AGENT_TEMPLATE.format(
            class_name=class_name,
            name=name,
            description=description,
            personality=personality,
            interval=interval,
            prompt=prompt,
            tools=tools,
            tags=tags
        )

        try:
            with open(file_path, "w") as f:
                f.write(content)
            logger.info("Successfully built and saved agent: %s at %s", name, file_path)
            return True
        except Exception as e:
            logger.error("Failed to save generated agent: %s", e)
            return False

builder_service = BuilderService()
